version: "2"

services:
  spark:
    build: .
    command: 'dev'
    ports:
      - 8082:80
    networks:
      - app
    volumes:
      - './src/:/var/www/html/app/'  

networks:
  app:
    driver: bridge